# InnoVault - Snapcraft Build - Known to build in most Ubuntu versions
# https://innovaultwallet.org
# https://github.com/innova-foundation/innovault
# By Carsen Klock
name: innovault
version: '1.9.9'
summary: InnoVault
description: |
  A Dashboard Interface and Wallet for Innova (INN), Ethereum (ETH), and USDT (USDT) built with NodeJS and Electron
grade: stable
confinement: strict

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes
 
apps:
  innovaultd:
    command: bin/node -r esm ./bin/innovault
    plugs: [home, network, network-bind]
    daemon: forking
  headless:
    command: bin/node -r esm ./bin/innovault
    plugs: [home, network, network-bind]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:/var/lib/snapd/desktop:$XDG_DATA_DIRS
      # Override HOME so the datadir is located at
      # ~/snap/innovault/common/InnoVault/ instead of
      # ~/snap/innovault/current/InnoVault/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  innovault:
    command: bin/node $SNAP/src/main.js
    plugs: [home, network, network-bind, unity7, wayland, desktop-legacy, desktop, x11, gsettings]
    desktop: innovault.desktop
    environment:
      QT_QPA_PLATFORMTHEME: gtk3
      XDG_DATA_DIRS: $SNAP_USER_DATA:/var/lib/snapd/desktop:$XDG_DATA_DIRS
      HOME: $SNAP_USER_COMMON
 
parts:
  headless:
    source: https://github.com/innova-foundation/innovault.git
    source-type: git
    source-tag: master
    plugin: nodejs
    node-engine: 12.16.3
    build-packages:
      - g++
      - jq
      - wget
      - unzip
      - curl
      - build-essential
    stage-packages:
      - g++
      - jq
      - wget
      - unzip
      - curl
      - build-essential
  innovault:
    source: https://github.com/innova-foundation/innovault.git
    source-type: git
    source-tag: master
    plugin: nodejs
    node-engine: 12.16.3
    build-packages:
      - g++
      - jq
      - wget
      - unzip
      - curl
      - build-essential
    stage-packages:
      - g++
      - jq
      - wget
      - unzip
      - curl
      - build-essential